#项目启动端口
server:
  port: 10077
spring:
  #连接mysql数据库
  datasource:
    url: jdbc:mysql://localhost:3306/shop?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  #连接elasticsearch
  data:
    elasticsearch:
      repositories:
        enabled: true
      cluster-nodes: 127.0.0.1:9300    #es的连接地址及端口号
      cluster-name:   elasticsearch    #es集群的名称
    mongodb:
      host: localhost   # Mongodb的连接地址
      port: 27017   # Mongodb的连接端口
      database: mall-port   # Mongodb的连接数据库

  #连接redis缓存数据库
  redis:
    host: localhost    #redis服务器地址
    database: 0        #redis数据库索引（默认为0）
    port: 6379         #redis服务器连接端口
    password:          #redis连接密码（默认为空）
    #redis连接池
    jedis:
      pool:
        max-wait: -1ms  #连接池最大阻塞等待时间（使用负值表示没有限制）
        min-idle: 0     #连接池中的最小空闲连接
        max-idle: 8     #连接池中的最大空闲连接
        max-active: 8   #连接池最大连接数（使用负值表示没有限制）
    timeout: 3000ms     #连接超时时间（毫秒）

#redis自定义配置
redis:
  key:
    prefix:
      authCode: "portal:authCode:"
    expire:
      authCode: 120

#mybatis映射xml文件路径
mybatis:
  mapper-locations:
    classpath: com/zzb/test/admin/*/*.xml

#jwt自定义配置
jwt:
  tokenHeader: Authorization  #JWT存储的请求头
  secret: mySecret            #JWT加解密使用的密钥
  expiration: 604800          #JWT的超期时间(60*60*24)
  tokenHead: Bearer           #JWT负载中拿到开头



