#项目启动端口
server:
  port: 10077
spring:
  #连接mysql数据库
  datasource:
    url: jdbc:mysql://localhost:3306/shop?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  #连接redis缓存数据库
  redis:
    host: localhost    #redis服务器地址
    database: 0        #redis数据库索引（默认为0）
    port: 6379         #redis服务器连接端口
    password:          #redis连接密码（默认为空）
    #redis连接池
    jedis:
      pool:
        max-wait: -1ms  #连接池最大阻塞等待时间（使用负值表示没有限制）
        min-idle: 0     #连接池中的最小空闲连接
        max-idle: 8     #连接池中的最大空闲连接
        max-active: 8   #连接池最大连接数（使用负值表示没有限制）
    timeout: 3000ms     #连接超时时间（毫秒）
  #redis自定义key
redis:
  key:
    prefix:
      authCode: "portal:authCode:"
    expire:
      authCode: 120
#mybatis映射xml文件路径
mybatis:
  mapper-locations:
    classpath: com/zzb/test/admin/mapper/*.xml



